import numpy as np
a=np.array([10,20,30])
b=np.array([2,3,4])
arr=np.array([10,20,30,40,50,100])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))